baseURL = "https://blog.writerswithoutwalls.com"
languageCode = "en"
title = "Writers Without Walls Blog"
theme = "congo"

[params]
  # Your brand colors
  mainSections = ["posts"]
  colorScheme = "dark" # matches your main site

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20
