baseURL = "https://blog.writerswithoutwalls.com"
languageCode = "en"
title = "Writers Without Walls Blog"
theme = "congo"

[params]
  colorScheme = "dark"

[params.theme]
  # Default mode
  defaultMode = "dark"

  # Dark mode colors
  [params.theme.dark]
    primary = "#FFD700"    # Gold
    secondary = "#C5A572"  # Secondary gold
    background = "#000000" # Black
    text = "#FFFFFF"       # White text
    accent = "#FFD700"     # Accent color

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20
